name = "ModFest 1.16"
author = "ModFest"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "042733745f6acb190df78dc324d97125ab4fbece5123f970762f09eafaa28663"

[versions]
fabric = "0.8.9+build.203"
minecraft = "1.16.1"
