name = "ModFest 1.16"
author = "ModFest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8002ccb1b3ae0f5c14f29093324ce1d1b40997073a999d8a349c971e8db27cef"

[versions]
fabric = "0.8.9+build.203"
minecraft = "1.16.1"
